---

- name: Internet
  apt:
    state: present
    name:
    # Navigateur web
    - firefox-esr
    - firefox-esr-l10n-fr
    - chromium
    - chromium-l10n
    # Client messagerie
    - thunderbird
    - thunderbird-l10n-fr
    # téléchargement audio video
    - yt-dlp
    # qr code wifi
    - wifi-qr

# deb12 à tester
- name: Internet | Extensions Navigateur
  apt:
    state: present
    name:
    - webext-ublock-origin-firefox
    - webext-ublock-origin-chromium
    - webext-privacy-badger
    #~ - webext-https-everywhere
    - webext-bulk-media-downloader
    
