---

#deb12- import_tasks: libreoffice_bpo.yml

- name: Bureautique | installation des paquets
  apt:
    state: present
    name:
    # Suite bureautique
    - libreoffice
    - libreoffice-gtk3
    - libreoffice-gnome
    - libreoffice-l10n-fr
    - libreoffice-help-fr
    - hyphen-fr
    - libreoffice-style-sifr
    - libreoffice-report-builder
    # Polices
    - ttf-mscorefonts-installer
    - fonts-liberation
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea
    - fonts-linex
# completer avec les polices windows >= vista
    - gnome-font-viewer
    # Pdf
    - evince
    - pdfsam
    - pdfarranger
    - bookletimposer
    - pdf-presenter-console
  tags: bureautique

- import_tasks: markdown.yml

- import_tasks: policevista.yml

- import_tasks: grammalecte.yml

- import_tasks: modeles.yml

- import_tasks: xournalpp.yml

- import_tasks: languagetool.yml

- import_tasks: libreoffice_config.yml
